---
 - name: Create an EC2 Instance
   hosts: localhost
   vars:
    image: ami-52d4802e
    region: ap-southeast-1
    instance_type: t2.micro
    key_name: id_rsa
  
   tasks:
   - name: Creating a EC2 instance
     ec2:
       image: "{{image}}"
       region: "{{region}}"
       instance_type: "{{instance_type}}"
       key_name: "{{key_name}}"
       state: "present"
       wait: true
#       register: ec2
  
#   - ec2_snapshot:
#       volume_id: ec2
#       description: take snaphot
#       register: snapshot

#  - local_action:
#      module: ec2_snapshot
#      snapshot_id: snapshot
#      state: absent
   
#   - name: Delete an EC2 instance
#     ec2:
#      region: "{{region}}"
#      state: "absent"
#      instance_ids: "{{ec2.instance_ids}}"

